//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CUKCUK.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CUKCUK.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không sử dụng.
        /// </summary>
        public static string VN_Device_No {
            get {
                return ResourceManager.GetString("VN_Device_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy in.
        /// </summary>
        public static string VN_Device_Printer {
            get {
                return ResourceManager.GetString("VN_Device_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy tính bảng.
        /// </summary>
        public static string VN_Device_Tablet {
            get {
                return ResourceManager.GetString("VN_Device_Tablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món không được phép để trống..
        /// </summary>
        public static string VN_DishCode_Empty {
            get {
                return ResourceManager.GetString("VN_DishCode_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món không được để trống..
        /// </summary>
        public static string VN_DishName_Empty {
            get {
                return ResourceManager.GetString("VN_DishName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string VN_Duplicate_DishCode {
            get {
                return ResourceManager.GetString("VN_Duplicate_DishCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã NVL &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string VN_Duplicate_MaterialCode {
            get {
                return ResourceManager.GetString("VN_Duplicate_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string VN_Duplicate_MenuGroupCode {
            get {
                return ResourceManager.GetString("VN_Duplicate_MenuGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string VN_Duplicate_MenuGroupName {
            get {
                return ResourceManager.GetString("VN_Duplicate_MenuGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính &lt;{0}&gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string VN_Duplicate_UnitName {
            get {
                return ResourceManager.GetString("VN_Duplicate_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã NVL không được phép để trống..
        /// </summary>
        public static string VN_MaterialCode_Empty {
            get {
                return ResourceManager.GetString("VN_MaterialCode_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên NVL không được phép để trống..
        /// </summary>
        public static string VN_MaterialName_Empty {
            get {
                return ResourceManager.GetString("VN_MaterialName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm thực đơn không được phép để trống..
        /// </summary>
        public static string VN_MenuGroupCode_Empty {
            get {
                return ResourceManager.GetString("VN_MenuGroupCode_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm thực đơn không được phép để trống..
        /// </summary>
        public static string VN_MenuGroupName_Empty {
            get {
                return ResourceManager.GetString("VN_MenuGroupName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra vui lòng liên hệ MISA để được hỗ trợ..
        /// </summary>
        public static string VN_Server_Error {
            get {
                return ResourceManager.GetString("VN_Server_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính không được phép để trống..
        /// </summary>
        public static string VN_Unit_Empty {
            get {
                return ResourceManager.GetString("VN_Unit_Empty", resourceCulture);
            }
        }
    }
}
